# This workflow will build a .NET project then run its unit tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: UnitTestCheck

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: API Tests
      run: dotnet test ./Tests/DNDWithin.API.Tests.Unit --no-build --verbosity normal
    - name: Application tests
      run: dotnet test ./Tests/DNDWithin.Application.Tests.Unit --no-build --verbosity normal
